# Generated by Django 3.2.5 on 2021-07-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigdeal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
